name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to Node.js 20 compatible version

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./"
          REMOTE_HOST: "206.189.231.7"
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: "/var/www/kokoplus.siteshowcase.top/"
