name: Deploy to Server

on:
  push:
    branches: [ master ]  # Ship changes to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose a different runner OS if needed
    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub

      - name: Setup SSH key  # Adds your SSH key securely
        uses: actions/upload-artifact@v3
        with:
          name: ssh-key
          path: ~/.ssh/id_rsa  # Replace with your private key path

      - name: Grant execute permissions  # Makes the SSH key executable
        run: chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server  # Connects and copies files
        uses: sshuttle/ssh-deploy@v4
        with:
          host: '206.189.231.7'  # Replace with your server IP
          username: 'manifest'  # Replace with your server username
          key: ${{ secrets.SSH_KEY }}  # Reference the uploaded SSH key
          deployTo: '/var/www/kokoplus.siteshowcase.top'  # Deployment directory

